application: northern-math-87323
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /css
  static_dir: css

- url: /templates
  static_dir: templates

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /
  static_files: index.html
  upload: index.html

- url: /(.*)
  static_files: \1
  upload: (.*)

- url: /plugins
  static_dir: plugins

- url: /.*
  script: xtremekm.application

